function build_ex18_sfw_top()
%BUILD_EX18_SFW_TOP 重新生成 ex18 的 RF Blockset 步进频率前端模型。

work_dir = fileparts(mfilename('fullpath'));
old_dir = pwd;
cleanup = onCleanup(@() cd(old_dir));
cd(work_dir);
addpath(work_dir);
addpath(fullfile(work_dir, 'filterlib'));
addpath(fullfile(work_dir, 'dialogs'));

setup_ex18_sfw();

model = 'ex18_sfw_top';
reset_model(model);
configure_model(model);

add_sfw_source(model);
add_source_monitor(model);
add_rf_chain(model);
add_rf_sinks(model);
add_gpr_receiver(model);
apply_filter_masks(model);
connect_model(model);
add_note(model);

save_system(model, fullfile(work_dir, [model '.slx']));
fprintf('Built %s.slx in %s\n', model, work_dir);
end

function reset_model(model)
if bdIsLoaded(model)
    close_system(model, 1);
end
new_system(model);
end

function configure_model(model)
init_cmd = [ ...
    'model_dir = fileparts(get_param(bdroot, ''FileName''));' ...
    'if ~isempty(model_dir), addpath(model_dir); addpath(fullfile(model_dir, ''filterlib'')); addpath(fullfile(model_dir, ''dialogs'')); end;' ...
    'setup_ex18_sfw;' ...
    ];

set_param(model, ...
    'StartTime', '0.0', ...
    'StopTime', 'sfw_stop_s', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'sfw_sample_s', ...
    'InitFcn', init_cmd, ...
    'SaveFormat', 'StructureWithTime', ...
    'ReturnWorkspaceOutputs', 'off');
end

function add_sfw_source(model)
add_block('simulink/Sources/From Workspace', [model '/SFW_Burst_Src'], ...
    'VariableName', 'sfw_src_ts', ...
    'SampleTime', 'sfw_sample_s', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [45 110 190 150]);
end

function add_source_monitor(model)
add_block('dspsnks4/Spectrum Analyzer', [model '/Spec_Src'], ...
    'InputDomain', 'Time', ...
    'SampleRateSource', 'Property', ...
    'SampleRate', 'sfw_fs_hz', ...
    'FrequencySpan', 'Start and stop frequencies', ...
    'StartFrequency', '0', ...
    'StopFrequency', '200e6', ...
    'FrequencyScale', 'Linear', ...
    'RBWSource', 'Property', ...
    'RBW', '100e3', ...
    'SpectrumType', 'Power', ...
    'SpectrumUnits', 'dBm', ...
    'PlotAsTwoSidedSpectrum', 'off', ...
    'ShowGrid', 'on', ...
    'OpenAtSimulationStart', 'off', ...
    'YLimits', '[-100 30]', ...
    'Title', 'SFW source spectrum, 0-200 MHz', ...
    'Position', [230 25 290 75]);

add_block('simulink/Sinks/Scope', [model '/Scope_SFW_Source'], ...
    'Position', [230 175 265 210]);
end

function add_rf_chain(model)
rf_cpl_s_text = mat2str(evalin('base', 'rf_cpl_s'), 17);
rf_cpl_freq_text = sprintf('%.17g', evalin('base', 'rf_cpl_freq_hz'));
rf_z0_text = sprintf('%.17g', evalin('base', 'rf_z0_ohm'));

add_block('simrfV2util1/Inport', [model '/RF_In'], ...
    'CarrierFreq', '0', ...
    'CarrierFreq_unit', 'Hz', ...
    'ZS', 'rf_z0_ohm', ...
    'InternalGrounding', 'on', ...
    'Position', [260 95 370 155]);

add_block('simrfV2elements/Attenuator', [model '/RF_Attn'], ...
    'Att', 'rf_attn_db', ...
    'Zin', 'rf_z0_ohm', ...
    'Zout', 'rf_z0_ohm', ...
    'AddNoise', 'on', ...
    'InternalGrounding', 'on', ...
    'Position', [640 95 770 155]);

add_block('simrfV2elements/Amplifier', [model '/RF_VGA'], ...
    'Zin', 'rf_z0_ohm', ...
    'Zout', 'rf_z0_ohm', ...
    'AddNoise', 'on', ...
    'InternalGrounding', 'on', ...
    'Position', [790 95 910 155]);

add_block('simrfV2elements/Amplifier', [model '/RF_PA'], ...
    'Zin', 'rf_z0_ohm', ...
    'Zout', 'rf_z0_ohm', ...
    'AddNoise', 'on', ...
    'InternalGrounding', 'on', ...
    'Position', [940 95 1060 155]);

add_block('simrfV2elements/S-parameters', [model '/RF_Coupler'], ...
    'DataSource', 'Network-parameters', ...
    'Paramtype', 'S-parameters', ...
    'Sparam', rf_cpl_s_text, ...
    'SparamFreq', rf_cpl_freq_text, ...
    'SparamFreq_unit', 'Hz', ...
    'SparamZ0', rf_z0_text, ...
    'InternalGrounding', 'on', ...
    'Position', [420 70 580 250]);

add_block('simrfV2_lib/Elements/R_RF', [model '/Iso_Term'], ...
    'R', 'rf_z0_ohm', ...
    'R_unit', 'Ohm', ...
    'Position', [420 300 490 340]);

add_block('simrfV2_lib/Elements/Electrical Reference', [model '/Gnd'], ...
    'Position', [430 375 480 410]);

add_block('simrfV2util1/Configuration', [model '/RF_Config'], ...
    'StepSize', 'sfw_sample_s', ...
    'StepSize_unit', 's', ...
    'Position', [260 255 390 325]);

apply_amp_masks(model);
end

function add_rf_sinks(model)
add_block('simrfV2util1/Outport', [model '/RF_Out'], ...
    'CarrierFreq', '0', ...
    'StepSize', 'sfw_sample_s', ...
    'StepSize_unit', 's', ...
    'ZL', 'rf_z0_ohm', ...
    'InternalGrounding', 'on', ...
    'Position', [1060 95 1175 155]);

add_block('simrfV2util1/Outport', [model '/RF_Tap_Out'], ...
    'CarrierFreq', '0', ...
    'StepSize', 'sfw_sample_s', ...
    'StepSize_unit', 's', ...
    'ZL', 'rf_z0_ohm', ...
    'InternalGrounding', 'on', ...
    'Position', [640 215 755 275]);

add_block('simulink/Sinks/Scope', [model '/Scope_TX_Radiated'], ...
    'Position', [1410 35 1450 75]);

add_block('simulink/Sinks/Scope', [model '/Scope_RF_Main_Out'], ...
    'DataLogging', 'on', ...
    'DataLoggingVariableName', 'rf_main_out_log', ...
    'Position', [1190 35 1230 75]);

add_block('simulink/Sinks/Scope', [model '/Scope_Tap_Upconverted'], ...
    'Position', [1510 220 1550 260]);

add_block('simulink/Sinks/To Workspace', [model '/Log_RF'], ...
    'VariableName', 'rf_out_log', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [1410 160 1510 190]);

add_block('simulink/User-Defined Functions/MATLAB System', [model '/TX_Radiator'], ...
    'System', 'phased.Radiator', ...
    'Sensor', 'phased.IsotropicAntennaElement', ...
    'OperatingFrequency', 'mean(sfw_freq_hz)', ...
    'CombineRadiatedSignals', 'on', ...
    'Position', [1235 85 1365 150]);

add_block('simulink/Sources/Constant', [model '/Radiation_Angle'], ...
    'Value', '[0;0]', ...
    'Position', [1175 165 1240 200]);

add_block('simulink/Sources/Sine Wave', [model '/Tap_LO_200MHz'], ...
    'Amplitude', 'tap_lo_amp', ...
    'Bias', '0', ...
    'Frequency', '2*pi*tap_lo_hz', ...
    'Phase', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'Position', [1070 330 1200 370]);

add_block('simulink/Math Operations/Product', [model '/Tap_Mixer_200MHz'], ...
    'Inputs', '**', ...
    'Position', [1190 225 1235 275]);

add_block('simulink/Discrete/Discrete Filter', [model '/Tap_Up_BPF'], ...
    'Numerator', 'tap_up_bpf_num', ...
    'Denominator', 'tap_up_bpf_den', ...
    'InitialStates', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'Position', [1295 210 1465 290]);

add_block('simulink/Sinks/To Workspace', [model '/Log_Tap'], ...
    'VariableName', 'tap_up_log', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [1510 280 1610 310]);
end

function add_gpr_receiver(model)
add_gpr_channel([model '/GPR_Channel'], [1385 85 1545 205]);

add_block('simulink/User-Defined Functions/MATLAB System', [model '/RX_Antenna'], ...
    'System', 'phased.Collector', ...
    'Sensor', 'phased.IsotropicAntennaElement', ...
    'OperatingFrequency', 'mean(sfw_freq_hz)', ...
    'Position', [1625 85 1760 155]);

add_block('simulink/Sources/Constant', [model '/RX_Angle'], ...
    'Value', 'gpr_rx_angle_deg', ...
    'Position', [1545 190 1610 225]);

add_block('simulink/Math Operations/Product', [model '/RX_Down_Mixer'], ...
    'Inputs', '**', ...
    'Position', [1830 105 1875 155]);

add_block('simulink/Discrete/Discrete Filter', [model '/RX_Down_IF_BPF'], ...
    'Numerator', 'rx_down_if_bpf_num', ...
    'Denominator', 'rx_down_if_bpf_den', ...
    'InitialStates', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'Position', [1930 80 2100 180]);

add_block('simulink/Sinks/Scope', [model '/Scope_RX_Down_IF'], ...
    'Position', [2160 90 2200 130]);

add_block('simulink/Sinks/To Workspace', [model '/Log_RX'], ...
    'VariableName', 'rx_down_if_log', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [2155 145 2255 175]);

add_block('simulink/Math Operations/Complex to Real-Imag', [model '/IF_to_Real'], ...
    'Position', [2105 200 2165 260]);

add_block('simulink/Sources/Sine Wave', [model '/Final_LO_200MHz'], ...
    'Amplitude', 'iq_lo_amp', ...
    'Bias', '0', ...
    'Frequency', '2*pi*iq_lo_hz', ...
    'Phase', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'Position', [1980 285 2110 325]);

add_block('simulink/Sources/Sine Wave', [model '/Final_LO_200MHz_Q'], ...
    'Amplitude', 'iq_lo_amp', ...
    'Bias', '0', ...
    'Frequency', '2*pi*iq_lo_hz', ...
    'Phase', '-pi/2', ...
    'SampleTime', 'sfw_sample_s', ...
    'Position', [1980 355 2110 395]);

add_block('simulink/Math Operations/Product', [model '/Mixer_I'], ...
    'Inputs', '**', ...
    'Position', [2140 195 2185 245]);

add_block('simulink/Math Operations/Product', [model '/Mixer_Q'], ...
    'Inputs', '**', ...
    'Position', [2140 305 2185 355]);

add_block('simulink/Discrete/Discrete FIR Filter', [model '/LPF_I'], ...
    'Coefficients', 'iq_lpf_num', ...
    'InitialStates', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'InputProcessing', 'Elements as channels (sample based)', ...
    'Position', [2250 180 2420 260]);

add_block('simulink/Discrete/Discrete FIR Filter', [model '/LPF_Q'], ...
    'Coefficients', 'iq_lpf_num', ...
    'InitialStates', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'InputProcessing', 'Elements as channels (sample based)', ...
    'Position', [2250 300 2420 380]);

add_block('simulink/Math Operations/Real-Imag to Complex', [model '/Real-Imag_to_Complex'], ...
    'Position', [2500 220 2580 290]);

add_block('simulink/Sinks/Scope', [model '/Scope_RX_IQ_Baseband'], ...
    'DataLogging', 'on', ...
    'DataLoggingVariableName', 'rx_iq_scope_log', ...
    'Position', [2640 220 2680 260]);

add_block('simulink/Sinks/To Workspace', [model '/Log_RX_IQ'], ...
    'VariableName', 'rx_iq_baseband_log', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [2640 280 2760 310]);

add_block('simulink/Sinks/To Workspace', [model '/Log_RX_Antenna'], ...
    'VariableName', 'rx_antenna_log', ...
    'SaveFormat', 'Structure With Time', ...
    'Position', [1625 175 1745 205]);
end

function add_gpr_channel(subsystem_path, position)
add_block('simulink/Ports & Subsystems/Subsystem', subsystem_path, ...
    'Position', position);
clear_subsystem(subsystem_path);

add_block('simulink/Sources/In1', [subsystem_path '/In1'], ...
    'Position', [35 145 65 165]);
add_block('simulink/Sinks/Out1', [subsystem_path '/Out1'], ...
    'Position', [525 145 555 165]);

add_block('simulink/Discrete/Discrete FIR Filter', [subsystem_path '/GPR_Channel_FIR'], ...
    'CoefSource', 'Dialog parameters', ...
    'Coefficients', 'gpr_soil_fir', ...
    'InitialStates', '0', ...
    'SampleTime', 'sfw_sample_s', ...
    'InputProcessing', 'Elements as channels (sample based)', ...
    'Position', [190 118 385 192]);

add_line(subsystem_path, 'In1/1', 'GPR_Channel_FIR/1', 'autorouting', 'on');
add_line(subsystem_path, 'GPR_Channel_FIR/1', 'Out1/1', 'autorouting', 'on');

Simulink.Annotation(subsystem_path, ...
    '土壤模型 FIR：由均匀有损土壤、地表反射、弱杂波和管道目标频响转换得到。');
end

function clear_subsystem(subsystem_path)
try
    Simulink.SubSystem.deleteContents(subsystem_path);
catch
    blocks = find_system(subsystem_path, 'SearchDepth', 1, 'Type', 'Block');
    for idx = 2:numel(blocks)
        delete_block(blocks{idx});
    end
end
end

function connect_model(model)
phs = get_param([model '/SFW_Burst_Src'], 'PortHandles');
phr = get_param([model '/RF_In'], 'PortHandles');
add_line(model, phs.Outport(1), phr.Inport(1), 'autorouting', 'on');

add_line(model, 'SFW_Burst_Src/1', 'Spec_Src/1', 'autorouting', 'on');
add_line(model, 'SFW_Burst_Src/1', 'Scope_SFW_Source/1', 'autorouting', 'on');

add_line(model, 'RF_In/RConn1', 'RF_Coupler/LConn1', 'autorouting', 'on');
add_line(model, 'RF_Coupler/RConn1', 'RF_Attn/LConn1', 'autorouting', 'on');
add_line(model, 'RF_Attn/RConn1', 'RF_VGA/LConn1', 'autorouting', 'on');
add_line(model, 'RF_VGA/RConn1', 'RF_PA/LConn1', 'autorouting', 'on');
add_line(model, 'RF_PA/RConn1', 'RF_Out/LConn1', 'autorouting', 'on');

add_line(model, 'RF_Coupler/RConn2', 'RF_Tap_Out/LConn1', 'autorouting', 'off');
add_line(model, 'RF_Coupler/LConn2', 'Iso_Term/RConn1', 'autorouting', 'off');
add_line(model, 'Iso_Term/LConn1', 'Gnd/LConn1', 'autorouting', 'on');

add_line(model, 'RF_Config/LConn1', 'RF_In/RConn1', 'autorouting', 'on');

add_line(model, 'RF_Out/1', 'TX_Radiator/1', 'autorouting', 'on');
add_line(model, 'RF_Out/1', 'Scope_RF_Main_Out/1', 'autorouting', 'on');
add_line(model, 'Radiation_Angle/1', 'TX_Radiator/2', 'autorouting', 'on');
add_line(model, 'TX_Radiator/1', 'Scope_TX_Radiated/1', 'autorouting', 'on');
add_line(model, 'TX_Radiator/1', 'Log_RF/1', 'autorouting', 'on');
add_line(model, 'TX_Radiator/1', 'GPR_Channel/1', 'autorouting', 'on');
add_line(model, 'GPR_Channel/1', 'RX_Antenna/1', 'autorouting', 'on');
add_line(model, 'RX_Angle/1', 'RX_Antenna/2', 'autorouting', 'on');
add_line(model, 'RX_Antenna/1', 'RX_Down_Mixer/1', 'autorouting', 'on');
add_line(model, 'RX_Antenna/1', 'Log_RX_Antenna/1', 'autorouting', 'on');
add_line(model, 'RF_Tap_Out/1', 'Tap_Mixer_200MHz/1', 'autorouting', 'on');
add_line(model, 'Tap_LO_200MHz/1', 'Tap_Mixer_200MHz/2', 'autorouting', 'on');
add_line(model, 'Tap_Mixer_200MHz/1', 'Tap_Up_BPF/1', 'autorouting', 'on');
add_line(model, 'Tap_Up_BPF/1', 'Scope_Tap_Upconverted/1', 'autorouting', 'on');
add_line(model, 'Tap_Up_BPF/1', 'Log_Tap/1', 'autorouting', 'on');
add_line(model, 'Tap_Up_BPF/1', 'RX_Down_Mixer/2', 'autorouting', 'on');
add_line(model, 'RX_Down_Mixer/1', 'RX_Down_IF_BPF/1', 'autorouting', 'on');
add_line(model, 'RX_Down_IF_BPF/1', 'Scope_RX_Down_IF/1', 'autorouting', 'on');
add_line(model, 'RX_Down_IF_BPF/1', 'Log_RX/1', 'autorouting', 'on');
add_line(model, 'RX_Down_IF_BPF/1', 'IF_to_Real/1', 'autorouting', 'on');
add_line(model, 'IF_to_Real/1', 'Mixer_I/1', 'autorouting', 'on');
add_line(model, 'IF_to_Real/1', 'Mixer_Q/1', 'autorouting', 'on');
add_line(model, 'Final_LO_200MHz/1', 'Mixer_I/2', 'autorouting', 'on');
add_line(model, 'Final_LO_200MHz_Q/1', 'Mixer_Q/2', 'autorouting', 'on');
add_line(model, 'Mixer_I/1', 'LPF_I/1', 'autorouting', 'on');
add_line(model, 'Mixer_Q/1', 'LPF_Q/1', 'autorouting', 'on');
add_line(model, 'LPF_I/1', 'Real-Imag_to_Complex/1', 'autorouting', 'on');
add_line(model, 'LPF_Q/1', 'Real-Imag_to_Complex/2', 'autorouting', 'on');
add_line(model, 'Real-Imag_to_Complex/1', 'Scope_RX_IQ_Baseband/1', 'autorouting', 'on');
add_line(model, 'Real-Imag_to_Complex/1', 'Log_RX_IQ/1', 'autorouting', 'on');
end

function add_note(model)
note = Simulink.Annotation(model, ...
    'Tap branch upconversion -> RX downconversion -> I/Q demod: RF_Tap_Out -> Tap_Up_BPF -> RX_Down_Mixer -> RX_Down_IF_BPF -> Mixer_I/Q -> LPF_I/Q -> Complex');
note.Position = [45 455 900 500];
end

function apply_amp_masks(model)
vga_path = [model '/RF_VGA'];
pa_path = [model '/RF_PA'];

try Simulink.Mask.get(vga_path).delete(); catch; end
set_param(vga_path, 'Source_linear_gain', 'Available power gain');
set_param(vga_path, 'linear_gain', 'rf_vga_gain_db');
set_param(vga_path, 'NF', 'rf_vga_nf_db');
set_param(vga_path, 'OpenFcn', 'ex18_amp_dialog(gcb);');
fprintf('RF_VGA: double-click to edit gain.\n');

try Simulink.Mask.get(pa_path).delete(); catch; end
set_param(pa_path, 'Source_linear_gain', 'Available power gain');
set_param(pa_path, 'linear_gain', 'rf_pa_gain_db');
set_param(pa_path, 'NF', 'rf_pa_nf_db');
set_param(pa_path, 'OpenFcn', 'ex18_amp_dialog(gcb);');
fprintf('RF_PA: double-click to edit gain.\n');
end

function apply_filter_masks(model)
tap_bpf = [model '/Tap_Up_BPF'];
rx_if_bpf = [model '/RX_Down_IF_BPF'];
lpf_i = [model '/LPF_I'];
lpf_q = [model '/LPF_Q'];

set_param(tap_bpf, 'OpenFcn', 'ex18_filter_dialog(gcb);');
set_param(rx_if_bpf, 'OpenFcn', 'ex18_filter_dialog(gcb);');
set_param(lpf_i, 'OpenFcn', 'ex18_filter_dialog(gcb);');
set_param(lpf_q, 'OpenFcn', 'ex18_filter_dialog(gcb);');
fprintf('Filters: double-click to edit cutoff parameters.\n');
end
